version: "3.9"

services:
  web:
    # build: .
    image: $DOCKER_USERNAME/azure-infrastructure-as-code-flask:latest
    command: ["gunicorn", "--bind", "0.0.0.0:$WEBSITES_PORT", "wsgi"]
    ports:
      - "8000:$WEBSITES_PORT"
    expose:
      - $WEBSITES_PORT
    env_file:
      - ./.env
